# Generated by Django 2.2.13 on 2020-08-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('lesson', models.CharField(max_length=50)),
                ('urlgenerated', models.CharField(max_length=50)),
            ],
        ),
    ]
