# Generated by Django 2.2.13 on 2020-08-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='hitcount',
            field=models.IntegerField(default=0),
        ),
    ]
