# Generated by Django 2.2.13 on 2020-08-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlgen', '0002_urldata_hitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='dateofhits',
            field=models.DateField(auto_now=True),
        ),
    ]
