# Generated by Django 2.2.13 on 2020-08-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlgen', '0003_urldata_dateofhits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='dateofhits',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
