# Generated by Django 2.2.13 on 2020-08-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlgen', '0006_auto_20200808_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='dateofhits',
            field=models.DateField(),
        ),
    ]
