# Generated by Django 3.0.7 on 2020-08-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='byuser',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
