# Generated by Django 2.2.1 on 2020-08-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_tasks_byuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
