# Generated by Django 3.0.7 on 2020-08-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(null=True)),
                ('byuser', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
