# Generated by Django 2.2.1 on 2020-08-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_submittask'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
