# Generated by Django 3.0.7 on 2020-08-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='passowrd',
            new_name='password',
        ),
    ]
