# Generated by Django 2.2.13 on 2020-08-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uniqueContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=200)),
                ('school_name', models.CharField(max_length=200)),
                ('content_unique_link', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.numberDailySchoolViews')),
            ],
        ),
    ]
