# Generated by Django 3.0.7 on 2020-08-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=20, unique=True)),
                ('passowrd', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
