# Generated by Django 2.2.1 on 2020-08-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200805_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchoolName', models.CharField(max_length=40, unique=True)),
                ('PhoneNumber', models.CharField(max_length=40, unique=True)),
                ('Board', models.CharField(max_length=40, unique=True)),
                ('Password', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
